// Survey vocabulary: class tokens and containers mapped to information
// units and levels, mirroring docs/mwu-html-survey/README.md. The inspector
// is read-only: it reports, it never emits Yomitan entries.

export interface UnitMapping {
  readonly unit: string;
  readonly level: number;
}

export const CLASS_TO_UNIT: Readonly<Record<string, UnitMapping>> = {
  hword: { unit: "headword-display", level: 1 },
  fl: { unit: "part-of-speech", level: 1 },
  lbs: { unit: "entry-qualifier", level: 1 },
  lb: { unit: "definition-label", level: 5 },
  vg: { unit: "sense-group", level: 2 },
  vd: { unit: "verb-subtype", level: 2 },
  sgram: { unit: "grammar-label", level: 3 },
  prs: { unit: "pronunciation", level: 1 },
  pr: { unit: "pronunciation-reading", level: 1 },
  l: { unit: "pronunciation-note", level: 1 },
  mw: { unit: "pronunciation-reading", level: 1 },
  "prt-a": { unit: "form-pronunciation", level: 1 },
  "play-pron": { unit: "pronunciation-audio", level: 1 },
  "hw-play-pron": { unit: "pronunciation-audio", level: 1 },
  "audio-icon": { unit: "pronunciation-audio", level: 1 },
  breakpoints: { unit: "headword-display", level: 1 },
  breakpoint: { unit: "headword-display", level: 1 },
  "no-hyphen": { unit: "headword-display", level: 1 },
  "headword-row": { unit: "inflection", level: 1 },
  if: { unit: "inflection-marker", level: 1 },
  spl: { unit: "inflection", level: 1 },
  "vg-ins": { unit: "inflection-group", level: 1 },
  il: { unit: "inflection-label", level: 1 },
  ix: { unit: "inflection-marker", level: 1 },
  etymology: { unit: "origin", level: 1 },
  et: { unit: "origin", level: 1 },
  mw_t_et_link: { unit: "cross-reference", level: 1 },
  toggle: { unit: "origin-section-title", level: 1 },
  sn: { unit: "sense-number", level: 3 },
  num: { unit: "sense-number", level: 3 },
  letter: { unit: "subsense-letter", level: 4 },
  "sense-(a)": { unit: "subsense-letter", level: 4 },
  "sense-(b)": { unit: "subsense-letter", level: 4 },
  "sub-num": { unit: "definition-number", level: 5 },
  sl: { unit: "sense-label", level: 3 },
  sls: { unit: "source-block-boundary", level: 3 },
  dt: { unit: "definition", level: 5 },
  sense: { unit: "definition", level: 3 },
  sen: { unit: "definition", level: 3 },
  pseq: { unit: "definition", level: 3 },
  sdsense: { unit: "sub-definition", level: 6 },
  sd: { unit: "sub-definition", level: 6 },
  uns: { unit: "usage-note", level: 6 },
  un: { unit: "usage-note", level: 6 },
  unText: { unit: "usage-note", level: 6 },
  "ex-sent-group": { unit: "example-sentence", level: 6 },
  "ex-sent": { unit: "example-sentence", level: 6 },
  vi: { unit: "example-sentence", level: 6 },
  vis: { unit: "example-sentence", level: 6 },
  auth: { unit: "example-source", level: 6 },
  source: { unit: "example-source", level: 6 },
  aq: { unit: "example-source", level: 6 },
  aqdate: { unit: "example-date", level: 6 },
  "dx-jump": { unit: "comparison-reference", level: 6 },
  mw_t_dxt: { unit: "comparison-reference", level: 6 },
  mw_t_sx: { unit: "cross-reference", level: 6 },
  mw_t_mat: { unit: "cross-reference", level: 1 },
  mw_t_a_link: { unit: "cross-reference", level: 6 },
  mw_t_i_link: { unit: "cross-reference", level: 6 },
  iw: { unit: "cross-reference", level: 1 },
  "cxl-ref": { unit: "variant-reference", level: 1 },
  cxl: { unit: "variant-reference", level: 1 },
  cxt: { unit: "variant-reference", level: 1 },
  dro: { unit: "phrase", level: 1 },
  drp: { unit: "phrase", level: 1 },
  vr: { unit: "alternate-form", level: 1 },
  va: { unit: "alternate-form", level: 1 },
  vl: { unit: "variant-qualifier", level: 1 },
  uro: { unit: "undefined-run-on", level: 1 },
  ure: { unit: "run-on-form", level: 1 },
  utxt: { unit: "undefined-run-on", level: 1 },
  "related-to": { unit: "related-item", level: 1 },
  mw_t_sc: { unit: "synonym-term", level: 1 },
  "see-in-addition": { unit: "see-in-addition", level: 1 },
  "sa-link": { unit: "see-in-addition", level: 1 },
  sc: { unit: "see-in-addition", level: 1 },
  usage: { unit: "see-in-addition", level: 6 },
  ca: { unit: "called-also", level: 6 },
  cat: { unit: "called-also", level: 6 },
  ucat: { unit: "called-also", level: 6 },
  pn: { unit: "called-also-number", level: 6 },
  syn: { unit: "synonym-discussion", level: 1 },
  "synonym-discussion": { unit: "synonym-discussion", level: 1 },
  srefs: { unit: "synonym-discussion-reference", level: 1 },
  sr: { unit: "synonym-discussion-reference", level: 1 },
  urefs: { unit: "usage-discussion-reference", level: 6 },
  ur: { unit: "usage-discussion-reference", level: 6 },
  mw_t_wi: { unit: "target-highlight", level: 6 },
  mw_t_sp: { unit: "target-highlight", level: 6 },
  "text-lowercase": { unit: "superscript-reference", level: 6 },
  "entry-status": { unit: "entry-status-image", level: 1 },
  illustrations: { unit: "illustration", level: 1 },
  caption: { unit: "illustration-caption", level: 1 },
  date: { unit: "phrase-date", level: 1 },
  "table-image": { unit: "table-image", level: 1 },
  "table-section": { unit: "table-reference", level: 1 },
  mw_t_bold: { unit: "strong", level: 6 },
};

// Presentation wrappers and containers without their own information unit.
export const PRESENTATION_CLASSES: readonly string[] = [
  "addPunct",
  "first-slash",
  "last-slash",
  "sents",
  "sents-inline",
  "sents-block",
  "toggle-icon",
  "visible-phone",
  "widget",
  "search-toolbar",
  "sub-well",
  "section-content",
  "def-accordion-sections",
  "def-wrapper",
  "wordclick",
  "left-content",
  "col-xl-12",
  "row",
  "entry-header",
  "page-content",
  "well",
  "content-body",
  "mw_t_bc",
  "sb-0",
  "sb-1",
  "sb-2",
  "sb-3",
  "no-sn",
  "has-sn",
  "has-num",
  "has-let",
  "has-subnum",
  "letter-only",
  "first-child",
  "firstVd",
  "mdash",
];

export const SEMANTIC_CONTAINERS: readonly string[] = [
  "mean",
  "dro",
  "drp",
  "vg",
  "vd",
  "sb",
  "sense",
  "sen",
  "pseq",
  "dt",
  "un",
  "uns",
  "related-to",
  "syn",
  "synonym-discussion",
  "illustrations",
  "table-section",
  "etymology",
  "prs",
  "prt-a",
  "vg-ins",
  "headword-row",
  "ex-sent-group",
];

export const KNOWN_TAGS: readonly string[] = [
  "mean",
  "mwu",
  "h1",
  "h2",
  "p",
  "div",
  "span",
  "sup",
  "em",
  "strong",
  "b",
  "a",
  "br",
  "img",
  "ul",
  "ol",
  "li",
  "link",
  "script",
];

export const IGNORED_UNITS: readonly string[] = [
  "pronunciation-audio",
  "entry-status-image",
  "illustration",
  "illustration-caption",
  "phrase-date",
  "table-image",
  "table-reference",
  "first-known-use",
];
